# This rule is not used by the project static-website itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to static.static.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: static-website
    app.kubernetes.io/managed-by: kustomize
  name: staticsite-viewer-role
rules:
- apiGroups:
  - static.static.com
  resources:
  - staticsites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - static.static.com
  resources:
  - staticsites/status
  verbs:
  - get
